alias a='./a.out'
alias main='vim main.c'
alias vimrc='vim ~/.vimrc'
alias bashrc='vim ~/.bashrc'
alias zshrc='vim ~/.zshrc'
alias 1r='gcc -xc -'
alias sdn='sudo shutdown -h now'
alias google='w3m google.co.jp'
alias ascii='man ascii'
alias src='source ~/.bashrc'
alias lc='ls --color=always'
alias grec='grep --color=always'
alias lesser='less -R'
alias jterm='xterm -cjk_width'
alias C='export LANG=C'
alias ja='export LANG=ja_JP.UTF-8'
alias linux='export TERM=linux'
alias exfb='export TERM=fberm'
